### PR TITLE
Add a 'row_filter' option to be able to filter rows based on field values

### PR DESCRIPTION
**Pull request by ESPNSTI**
This adds a 'row_filter' option that will include or exclude rows based on what a particular field value is.

If a field value matches the row_filter, the row is included, unless the row_filter is prefixed with '!', in which case the row is excluded.

If the row_filter is prefixed and suffixed with '/', then it is treated as a RegEx match rather than an exact value match.

If multiple fields are used in row_filter, it is treated as an AND, and all fields must match for the row to be included.

If row_filter is omitted, it does not impact performance.
If row_filter is used, it probably impacts performance, but I haven't noticed a significant difference.
The row_filter code performance probably can be improved by doing some steps only once per field rather than every time a row is processed.

### CODE REVIEW

**Comment by xxBedy** [comment]
This river is not general purpose ETL processor.
You can preprocess your date before import.
For example you can use awk for this, like:

#Ignore lines with empty string in second column
cat file.csv | awk -F, '{if( $2!="" ) {print $0} }'

**Comment by ESPNSTI** [comment]
Hi,

Thanks for writing this river, it's really helped me out and I'm going to use it heavily.

As for the row_filter, I'd like to be able to just drop a raw source file in a directory and have it import.

Without this, I'd need to create another process to either pre-process the files in another directory and then copy to the CSV river import directory, or to overwrite the source using "script_before_file".

Since I'm dealing with Windows environments, things like awk are not available without having to install something first.
While that isn't a huge deal, still it is one more thing that adds complexity that I was hoping to avoid.

On very large files, it is probably more efficient to filter while importing rather than pre-processing.

Does it really hurt to have this?
It's simple enough code, it doesn't impact performance if it's not used, and in my opinion it is more elegant and efficient than pre-processing files.

Thanks.

**Comment by vtajzich** [comment]
I agree with @xxBedy . It's about separation of concerns. This river is responsible for loading CSV to ES not for ETL. 

There are tools / frameworks designed to process any kind of big files and do whatever is needed.

**Comment by ESPNSTI** [comment]
Ok, fair enough, didn't hurt to ask. :)
Thanks for the consideration.

**Comment by vtajzich** [comment]
You're welcome :-)

**Pull request closed without merging**
